dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  sepolia:
    verify: True
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
  mainnet-fork-dev:
    verify: False
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"


wallets:
  from_key: ${PRIVATE_KEY}